export { default as healthCheck } from './healthCheck.controller.mjs';
export { default as undefinedRoute } from './undefinedRoute.controller.mjs';
export { default as globalError } from './globalError.controller.mjs';
export { default as adminController } from './admin/admin.controller.mjs';
export { default as getRegistrationsController } from './events/getRegistrations.controller.mjs';
export { default as createRegistrationsController } from './events/createRegistrations.controller.mjs';
export { default as creationsJudgesController } from './judges/creations.judges.controller.mjs';
export { default as gettingJudgesController } from './judges/getting.judges.controller.mjs'
export { default as createAllocationController } from './allocations/create.allocations.controller.mjs'
export { default as getAllocationController } from './allocations/getting.allocations.controller.mjs'